version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    container_name: books
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: books
      # You should definitely change the password in production
      POSTGRES_PASSWORD: books
      POSTGRES_USER: books
    ports:
      - 5432:5432
  php:
    container_name: php
    build:
      context: ./docker
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/symfony_docker
    depends_on:
      - database

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/symfony_docker
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
